apiVersion: v1
kind: Service
metadata:
  name: hct-vehiculo-svc
  namespace: hct-huaripaucar
spec:
  type: NodePort
  selector:
    app: hct-vehiculo
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
