apiVersion: apps/v1
kind: Deployment
metadata:
  name: hct-vehiculo
  namespace: hct-huaripaucar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hct-vehiculo
  template:
    metadata:
      labels:
        app: hct-vehiculo
    spec:
      containers:
        - name: hct-vehiculo
          image: jesushuaripaucarcardenas/hct-vehiculo:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_R2DBC_URL
              valueFrom:
                secretKeyRef: { name: hct-vehiculo-secret, key: R2DBC_URL }
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef: { name: hct-vehiculo-secret, key: R2DBC_USERNAME }
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef: { name: hct-vehiculo-secret, key: R2DBC_PASSWORD }
