apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepe-gonzales-deployment
  namespace: pepe-gonzales-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepe-gonzales-deployment
  template:
    metadata:
      labels:
        app: pepe-gonzales-deployment
    spec:
      containers:
      - name: pepe-gonzales-container
        image: jesushuaripaucarcardenas/practicados:latest
        imagePullPolicy: Always #never
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: pepe-gonzales-secret