server:
  port: 8083

spring:
  application:
    name: hct-alquiler
  r2dbc:
    url: r2dbc:postgresql://ep-polished-leaf-acn11qxh-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslMode=require
    username: neondb_owner
    password: npg_MNeK54wzgqdt

services:
  vehiculo-url: https://upgraded-meme-r4r56vj7px9x2xp7r-30081.app.github.dev
  cliente-url: https://upgraded-meme-r4r56vj7px9x2xp7r-30082.app.github.dev
