apiVersion: v1
kind: Secret
metadata:
  name: hct-cliente-secret
  namespace: hct-huaripaucar
type: Opaque
stringData:
  R2DBC_URL: "r2dbc:postgresql://ep-polished-leaf-acn11qxh-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslMode=require"
  R2DBC_USERNAME: "neondb_owner"
  R2DBC_PASSWORD: "npg_MNeK54wzgqdt"
