server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: practicados
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://emanuelsantix_db_user:SPGBOecUdmebkhjy@cluster0.umym4ox.mongodb.net/practicados?appName=Cluster0}
#server:
#postgresql
#  port: ${SERVER_PORT:8081}
#spring:
#  application:
#    name: practicados
#  r2dbc:
#    url: r2dbc:postgresql://${DB_HOST:ep-polished-leaf-acn11qxh-pooler.sa-east-1.aws.neon.tech}/${DB_NAME:neondb}?sslMode=require
#    username: ${DB_USERNAME:neondb_owner}
#    password: ${DB_PASSWORD:npg_MNeK54wzgqdt}