apiVersion: v1
kind: Service
metadata:
  name: hct-frontend-svc
  namespace: hct-huaripaucar
spec:
  type: NodePort
  selector:
    app: hct-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
